---
- hosts: 'localhost'
  become: true
  vars_files:
  - vars/alert-vars.yml

  tasks:
  - name: Download alertmanager
    unarchive:
      src: "https://github.com/prometheus/alertmanager/releases/download/v{{ version }}/alertmanager-{{ version }}.linux-amd64.tar.gz"
      dest: /tmp/
      remote_src: yes

  - name: Copy alertmanager binaries to /usr/local/bin
    copy:
      src: "/tmp/alertmanager-{{ version }}.linux-amd64/alertmanager"
      dest: "/usr/local/bin/alertmanager"
      owner: "{{userId}}"
      group: "{{groupId}}"
      remote_src: yes
      mode: 0755

  - name: Creates data directory
    file: 
      path: "/data/alertmanager/"
      state: directory
      owner: "{{userId}}"
      group: "{{groupId}}"
      mode: 0755

  - name: Creates config directory
    file: 
      path: "/etc/alertmanager/"
      state: directory
      owner: "{{userId}}"
      group: "{{groupId}}"
      mode: 0755

  - name: Copy config file
    copy:
      src: "./files/alertmanager.yml"
      dest: /etc/alertmanager/alertmanager.yml

  - name: Copy systemd init file
    template:
      src: "./template/alertmanager.service.js"
      dest: /etc/systemd/system/alertmanager.service

  - name: Start alertmanager service
    service:
      name: alertmanager
      state: started
      enabled: yes


