  
global:
  slack_api_url: "https://hooks.slack.com/services/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"

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
 # routes:
 # - match:
 #     alertname: Monitoring-alert
  routes:
  - match:
  receiver: 'alert-team'
 # continue: true
 # - match:
 # reciever: 'alert-team'
receivers:
- name: 'alert-team'
  slack_configs:
  - channel: "#promethesus"
    text: "summary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}"
#- name: 'mail-alert'
  email_configs: 
  - to: masih.osheen16@gmail.com
    from: masih.osheen16@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: "masih.osheen16@gmail.com"
    auth_identity: "masih.osheen16@gmail.com"
    auth_password: "privy=statue_fury"
